services:
  db:
    image: postgres:18.1-alpine
    container_name: unioloci-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/18/docker

  redis:
    image: redis:8.4-alpine
    container_name: unioloci-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
